### ISSUE TITLE
大佬，你的中文教程是借鉴的我的吧？

### ISSUE THREAD

**Issue by 892947707** [Sansui233/proxypoolCheck#15]
我说咋这么熟悉呢。proxypool怎么删库了，是被滥用恶心到了么

**Comment by Sansui233** [comment]
您是？中文教程是由 pr #10 的提交的，我改了改一点点翻译，并不知道来源。个人原因最近已没有精力维护了。没有删库，版本退回了，tag还在，需要个人编译。

**Comment by 892947707** [comment]
> 您是？中文教程是由 pr #10 的提交的，我改了改一点点翻译，并不知道来源。个人原因最近已没有精力维护了。没有删库，版本退回了，tag还在，需要个人编译。

没什么，早知道我也可以提交哈哈哈。我是1月份跟你商业互吹的那个。我学习一下编译最新版吧，感谢。

**Comment by 892947707** [comment]
好难啊，请问怎么编译呢？我已经下载好了代码，安装好了golang，进入文件夹make的时候还是会报错`recipe for target 'linux-amd64' failed`。可否说一下完整的命令？只是想尽量使用最新版，强迫症:rofl:

**Comment by Sansui233** [comment]
就只是make而已😅 具体还有报错别的吗

也可以源码运行，go run main.go ，按道理源码运行没问题make就不会有问题。

在 2021年4月26日，上午2:27，892947707 ***@***.***> 写道：

﻿

好难啊，请问怎么编译呢？我已经下载好了代码，安装好了golang，进入文件夹make的时候还是会报错recipe for target
'linux-amd64' failed。可否说一下完整的命令？只是想尽量使用最新版，强迫症🤣

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Sansui233/proxypoolCheck/issues/15#issuecomment-826368266>,
or unsubscribe

**Comment by 892947707** [comment]
go version
`go version go1.10.4 linux/amd64`
go run main.go
`main.go:9:2: cannot find package "github.com/Sansui233/proxypool/api" in any of:`
make
```
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
Makefile:36: recipe for target 'linux-amd64' failed
```
新建的虚拟机，应该不是环境问题吧

**Comment by Sansui233** [comment]
缺依赖。项目使用了go mod，Go version需要在1.11以上。而最新的clash依赖要求1.16。

升级完go的版本后在工作目录中下载依赖

```shell
go mod download
```

再使用make

892947707 ***@***.***>于2021年4月26日 周一上午10:49写道：

**Comment by Sansui233** [comment]
缺依赖。依赖管理使用了go mod，Go version需要在1.11以上。proxypool之前的Go version最低为1.14，而最新的引用的clash依赖要求1.16。所以最好用到1.16版本的Go

升级完go的版本后在工作目录中下载依赖

```shell
go mod download
```

再使用make

**Comment by 892947707** [comment]
成功了，确实是go的版本问题，花了几个小时才升级。感谢感谢！辛苦了
